apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-web-proxy
  labels:
    app: grpc-web-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-web-proxy
  template:
    metadata:
      labels:
        app: grpc-web-proxy
    spec:
      containers:
      - name: grpc-web-proxy
        image: shareddev.azurecr.io/grpc-envoy/v1
        #ports:
        #- name: web
          #containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: grpc-web-proxy
  labels:
    app: grpc-web-proxy
spec:
  selector:
    app: grpc-web-proxy
  #ports:
  #- name: web
    #port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-server
  labels:
    app: sensor-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-server
  template:
    metadata:
      labels:
        app: sensor-server
    spec:
      containers:
      - name: sensor-server
        image: shareddev.azurecr.io/sensor-server/v1
        ports:
        - name: web
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: sensor-server
  labels:
    app: sensor-server
spec:
  selector:
    app: sensor-server
  ports:
  - name: web
    port: 8080
  type: LoadBalancer