apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: sensor-service
spec:
  type: 0
  resourceID: /subscriptions/22dad228-206b-434c-be66-d19228f01226/resourceGroups/AKSSandboxMI/providers/Microsoft.ManagedIdentity/userAssignedIdentities/keda-operator-identity1
  clientID: 4f6d5141-9e70-4690-b51a-9c8d860d8a12
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: sensor-service
spec:
  azureIdentity: sensor-service
  selector: sensor-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-data
data:
  listener.address: "0.0.0.0"
  listener.port: "8000"
  cluster.address: "10.0.94.161"
  cluster.port: "8081"
  server.address: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-server
  labels:
    app: sensor-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-server
  template:
    metadata:
      labels:
        app: sensor-server
        aadpodidbinding: sensor-service
    spec:
      containers:
      - name: sensor-server
        image: acrsandbox1.azurecr.io/sensor-server:latest
        imagePullPolicy: Always
        env:
        - name: SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: envoy-data
              key: server.address
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: envoy-data
              key: cluster.port
        ports:
        - containerPort: 8081
          name: web
---
kind: Service
apiVersion: v1
metadata:
  name: sensor-server
  labels:
    app: sensor-server
spec:
  selector:
    app: sensor-server
  ports:
  - name: web
    targetPort: web
    port: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-web-proxy
  labels:
    app: grpc-web-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-web-proxy
  template:
    metadata:
      labels:
        app: grpc-web-proxy
    spec:
      containers:
      - name: grpc-web-proxy
        image: acrsandbox1.azurecr.io/grpc-envoy:latest
        imagePullPolicy: Always
        env:
        - name: LISTENER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: envoy-data
              key: listener.address
        - name: LISTENER_PORT
          valueFrom:
            configMapKeyRef:
              name: envoy-data
              key: listener.port
        - name: CLUSTER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: envoy-data
              key: cluster.address
        - name: CLUSTER_PORT
          valueFrom:
            configMapKeyRef:
              name: envoy-data
              key: cluster.port
        ports:
          - containerPort: 8000
            name: listener
          - containerPort: 8081
            name: cluster
---
kind: Service
apiVersion: v1
metadata:
  name: grpc-web-proxy
  labels:
    app: grpc-web-proxy
spec:
  selector:
    app: grpc-web-proxy
  ports:
  - name: web
    port: 8000
  type: LoadBalancer
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sensor-server
spec:
  scaleTargetRef:
    kind: Deployment
    name: sensor-server
  pollingInterval: 30                                # Optional. Default: 30 seconds
  cooldownPeriod:  300                               # Optional. Default: 300 seconds
  minReplicaCount: 1                                 # Optional. Default: 0
  maxReplicaCount: 100                               # Optional. Default: 100
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: true              # Optional. Default: false
  triggers:
  - type: azure-servicebus
    metadata:
      # Required: queueName OR topicName and subscriptionName
      queueName: keda-test1
      #subscriptionName: 'Microsoft Azure Internal Consumption' #sbtopic-sub1
      # Optional, required when pod identity is used
      namespace: akssandbox
      # Optional
      messageCount: "5" # Optional. Count of messages to trigger scaling on. Default: 5 messages
    authenticationRef:
        name: azure-servicebus-auth